(function() {var implementors = {};
implementors["auth"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["chain"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["chain_sync"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["forest_address"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["forest_blocks"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["forest_crypto"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["forest_ipld"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["forest_vm"] = [{"text":"impl Error for ActorError","synthetic":false,"types":[]}];
implementors["ipld_amt"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["ipld_hamt"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["key_management"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["message_pool"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["state_manager"] = [{"text":"impl Error for Error","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()